config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users
  root to: 'pages#home'
  resources :campaigns
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :publisher
  has_many :pannels
  has_many :prints
  has_many :radios
  has_many :televisions
  has_many :transports
  has_many :ad_bookings
end

app/models/ad_booking.rb
class AdBooking < ApplicationRecord
  belongs_to :campaign
  belongs_to :ad
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  #associations
  belongs_to :user
  has_many :ad_bookings
end

app/models/pannel.rb
class Pannel < ApplicationRecord
  belongs_to :ad
  belongs_to :target
  has_one :publisher, through: :ad
end

app/models/print.rb
class Print < ApplicationRecord
  belongs_to :ad
  belongs_to :target
  has_one :publisher, through: :ad
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :ads
end

app/models/radio.rb
class Radio < ApplicationRecord
  belongs_to :ad
  belongs_to :target
  has_one :publisher, through: :ad
end

app/models/target.rb
class Target < ApplicationRecord
  has_many :pannels
  has_many :prints
  has_many :televisions
  has_many :radios
  has_many :transports
end

app/models/television.rb
class Television < ApplicationRecord
  belongs_to :ad
  belongs_to :target
  has_one :publisher, through: :ad
end

app/models/transport.rb
class Transport < ApplicationRecord
  belongs_to :ad
  belongs_to :target
  has_one :publisher, through: :ad
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :campaigns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = current_user.campaigns
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user
    if @campaign.save
        redirect_to campaign_path(@campaign)
    else
      render :new
    end
  end


  def campaign_params
    params.require(:campaign).permit(:name, :budget, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campaigns/_form_campaign.html.erb
<%= simple_form_for(@campaign) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :budget, as: :integer %>
  <%= f.input :start_date, as: :datetime %>
  <%= f.input :end_date, as: :datetime %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/campaigns/index.html.erb
<h1>Campagnes de communication:</h1>

<ul>
  <% @campaigns.each do |campaign| %>
    <li><%= link_to campaign.name, campaign_path(campaign) %></li>
  <% end %>
</ul>


<%= link_to "Créer une campagne",  new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>Nouvelle campagne</h1>
<%= render 'form_campaign' %>

app/views/campaigns/show.html.erb
<h1><%= @campaign.name %></h1>
<ul>
  <li><b>Budget:</b><%= @campaign.budget %> €</li>
  <li><b>Date de début :</b><%= @campaign.start_date %></li>
  <li><b>Date de fin :</b><%= @campaign.end_date %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <span class="title-home">DATARKETING</span>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>